```{r}
dateToRange <- function (range){
  
}
```

```{r}
data <- read.csv("OSMI Mental Health in Tech Survey 2017-18.csv", header=TRUE)

levels(data$How.many.employees.does.your.company.or.organization.have.) <- c(levels(data$How.many.employees.does.your.company.or.organization.have.), "1-5", "6-25")
data$How.many.employees.does.your.company.or.organization.have.[data$How.many.employees.does.your.company.or.organization.have.=="5-Jan"] <- "1-5"
data$How.many.employees.does.your.company.or.organization.have.[data$How.many.employees.does.your.company.or.organization.have.=="25-Jun"] <- "6-25"

data
```

```{r}
head(data)
```

```{r}
str(data)
```



Data Cleanup: Gender

Resources:
https://www.genderspectrum.org/quick-links/understanding-gender/
https://en.wikipedia.org/wiki/Non-binary_gender

```{r}
table(data$What.is.your.gender.)
```
```{r}
cis_female <- c( 'Female', 'female', 'Female ', 'Woman', 'woman', 'F', 'f', 'I identify as female', '*shrug emoji* (F)', 'Cis woman', 'Female (cisgender)', 'Cis-Female', 'Cisgendered woman', 'She/her/they/them', 'Cis female', 'cisgender female', 'femalw', 'femail', 'female (cis)', 'My sex is female.', 'female (cisgender)', 'Female (cis) ', 'Woman-identified', 'cis-Female', 'cis female', 'F, cisgender', 'Cis female ')

cis_male <- c('male', 'Male', 'Ostensibly Male', 'male, born with xy chromosoms', 'Malel', 'M', 'MALE', 'm', 'Cis-male', 'Male ', 'cis male ', 'Cis Male', 'Man', 'Cisgender male', 'cis-male', 'Mail', 'cis hetero male', 'Male (cis)', "male (hey this is the tech industry you're talking about)", 'God King of the Valajar', 'Cis male', 'man', 'Male, cis', 'cis male', 'dude' , 'SWM')


transgender <- c('transgender', 'Trans woman', 'Trans female', 'trans woman', 'Transfeminine', 'Trans man')

gq <- c('male/androgynous ', 'Agender', '', 'Nonbinary', 'Male (or female, or both)', 'non binary', 'Female/gender non-binary.', 'N/A', 'genderfluid', 'Genderqueer', 'Demiguy', 'none', 'non-binary', 'Other', 'NB', 'Genderfluid', 'Nonbinary/femme', 'gender non-conforming woman', 'uhhhhhhhhh fem genderqueer?', 'n/a', 'Non-binary', 'Agender/genderfluid', 'Male-ish', 'sometimes', 'Contextual', 'Non binary', 'Genderqueer demigirl', 'Genderqueer/non-binary', 'nonbinary', 'Female-ish', '\\-', 'None')
```

```{r}
gender <- as.vector(data$What.is.your.gender.)
n <- length(gender)
for(i in 1:n){
  if(gender[i] %in% cis_female){
    gender[i] <- "cis-female"
  }else if (gender[i] %in% gq){
    gender[i] <- "genderqueer"
  }else if (gender[i] %in% transgender){
    gender[i] <- "transgender"
  }else if (gender[i] %in% cis_male){
    gender[i] <- "cis-male"
  }else{
    gender[i]
  }
}

```

```{r}
table(gender)
```

```{r}
data$What.is.your.gender. <- gender
```

```{r}
table(data$What.is.your.gender.)
```

